---
title: Miru Travel Blog
email: mirug@gmail.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  homepage:
    title: homepage
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
markdown: kramdown
permalink: /:title
description: Dogtown Daily is a blog dedicated to all things Venice Beach, CA. Join
  us as we explore every bakery, restaurant, walk street and canal this great area
  of LA has to offer.
