---
title: Miru
<<<<<<< HEAD
url: http://miru.world
=======
>>>>>>> origin/master
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
<<<<<<< HEAD
permalink: /:year/:month/:title
description: Miru World is a travel journal curated by a young adventurous couple. Venice, CA is home.
=======
url: http://miru.world
permalink: "/:title"
description: Miru World is a travel journal curated by a young adventurous couple.
  Venice, CA is home.
>>>>>>> origin/master
