---
title: Miru Travel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  author:
    title: authors
    output: true
  tag:
    title: tags
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: "/:title/"
url: http://miru.world
description: Miru World is a travel journal curated by a young adventurous couple.
  Venice, CA is home.
about: Welcome to Miru World, our quaint little corner of the internet we call home.
