---
title: Miru World
url: http://miru.world
timezone: UTC
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: Miru World is a travel journal curated by a young adventurous couple.
  Venice, CA is home.
