source 'https://rubygems.org'

gem 'rake'
gem 'neat'
gem 'foreman'
gem 'kramdown'
gem 'rack'
gem 'siteleaf'
gem 'racksh'
gem 'compass-normalize'
gem 'susy'
gem 'guard-coffeescript'
gem 'guard-jammit'
gem 'jekyll-sass-converter'
gem 'jekyll-watch'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll', '~> 3.0', '>= 3.0.3'
gem 'rubyzip', require: 'zip/zip'
